Extrator de DREs de Empresas listadas na B3

In [1]:
!pip install wget

Requirement already satisfied: wget in /usr/local/lib/python3.12/dist-packages (3.2)

In [2]:
import pandas as pd
import wget
from zipfile import ZipFile

In [3]:
cvm = "https://dados.cvm.gov.br/"
url = "https://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/DADOS/"

In [4]:
arq_zip = []

for ano in range(2010, 2026):
  arq_zip.append(f'dfp_cia_aberta_{ano}.zip')

arq_zip

['dfp_cia_aberta_2010.zip',
 'dfp_cia_aberta_2011.zip',
 'dfp_cia_aberta_2012.zip',
 'dfp_cia_aberta_2013.zip',
 'dfp_cia_aberta_2014.zip',
 'dfp_cia_aberta_2015.zip',
 'dfp_cia_aberta_2016.zip',
 'dfp_cia_aberta_2017.zip',
 'dfp_cia_aberta_2018.zip',
 'dfp_cia_aberta_2019.zip',
 'dfp_cia_aberta_2020.zip',
 'dfp_cia_aberta_2021.zip',
 'dfp_cia_aberta_2022.zip',
 'dfp_cia_aberta_2023.zip',
 'dfp_cia_aberta_2024.zip',
 'dfp_cia_aberta_2025.zip']

In [5]:
for arq in arq_zip:
  wget.download(url+arq)

In [6]:
for arq in arq_zip:
  ZipFile(arq, 'r').extractall('CVM')

In [7]:
!mkdir DADOS

mkdir: cannot create directory ‘DADOS’: File exists

In [8]:
nomes = [
    # 'BPA_con', 'BPA_ind'
    # ,'BPP_con', 'BPP_ind'
    # ,'DFC_MD_con', 'DFC_MD_ind'
    # ,'DFC_MI_con', 'DFC_MI_ind'
    # ,'DMPL_con', 'DMPL_ind'
    # ,'DRA_con', 'DRA_ind'
    'DRE_con', 'DRE_ind'
    # ,'DVA_con', 'DVA_ind'
    ]

for nome in nomes:
  arquivo = pd.DataFrame()
  for ano in range(2011, 2026):
    arquivo = pd.concat([arquivo, pd.read_csv(f'/content/CVM/dfp_cia_aberta_{nome}_{ano}.csv', sep = ';', decimal = ',', encoding = 'ISO-8859-1')])
  arquivo.to_csv(f'DADOS/dfp_cia_aberta_{nome}_2010-2025', index = False)

In [9]:
dre = pd.read_csv('/content/DADOS/dfp_cia_aberta_DRE_con_2010-2025')
dre.head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.000.000/0001-91,2011-12-31,4,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2010-01-01,2010-12-31,3.01,Receitas da Intermediação Financeira,85143206.0,S
1,00.000.000/0001-91,2011-12-31,4,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.01,Receitas da Intermediação Financeira,106919760.0,S
2,00.000.000/0001-91,2011-12-31,4,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2010-01-01,2010-12-31,3.01.01,Receita de Juros,85143206.0,S

In [10]:
dre = dre[dre['ORDEM_EXERC'] == 'ÚLTIMO']
dre.head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
1,00.000.000/0001-91,2011-12-31,4,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.01,Receitas da Intermediação Financeira,106919760.0,S
3,00.000.000/0001-91,2011-12-31,4,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.01.01,Receita de Juros,106919760.0,S
5,00.000.000/0001-91,2011-12-31,4,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.02,Despesas da Intermediação Financeira,-69976075.0,S

In [ ]:
empresas = dre[['DENOM_CIA', 'CD_CVM']].drop_duplicates().set_index('CD_CVM')
empresas

# EMBRAER: 20087
# BRF: 16292
# VALE: 4170

In [14]:
embraer = dre[dre['CD_CVM'] == 20087]
embraer.head()

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
7599,07.689.002/0001-89,2011-12-31,3,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.01,Receita de Venda de Bens e/ou Serviços,9858055.0,S
7601,07.689.002/0001-89,2011-12-31,3,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.02,Custo dos Bens e/ou Serviços Vendidos,-7638825.0,S
7603,07.689.002/0001-89,2011-12-31,3,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.03,Resultado Bruto,2219230.0,S
7605,07.689.002/0001-89,2011-12-31,3,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.04,Despesas/Receitas Operacionais,-1697502.0,S
7607,07.689.002/0001-89,2011-12-31,3,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.04.01,Despesas com Vendas,-702866.0,S

In [15]:
embraer[['CD_CONTA', 'DS_CONTA']].drop_duplicates().set_index('CD_CONTA')

                                                     DS_CONTA
CD_CONTA
3.01                   Receita de Venda de Bens e/ou Serviços
3.02                    Custo dos Bens e/ou Serviços Vendidos
3.03                                          Resultado Bruto
3.04                           Despesas/Receitas Operacionais
3.04.01                                   Despesas com Vendas
3.04.02                     Despesas Gerais e Administrativas
3.04.03            Perdas pela Não Recuperabilidade de Ativos
3.04.04                          Outras Receitas Operacionais
3.04.05                          Outras Despesas Operacionais
3.04.05.01                                           Pesquisa
3.04.05.02                              Despesas Operacionais
3.04.06                 Resultado de Equivalência Patrimonial
3.05        Resultado Antes do Resultado Financeiro e dos ...
3.06                                     Resultado Financeiro
3.06.01                                  Receitas Financeiras
3.06.01.01                        Variações Monetárias Ativas
3.06.01.02                               Receitas Financeiras
3.06.02                                  Despesas Financeiras
3.06.02.01                      Variações Monetárias Passivas
3.06.02.02                               Despesas Financeiras
3.07               Resultado Antes dos Tributos sobre o Lucro
3.08        Imposto de Renda e Contribuição Social sobre o...
3.08.01                                              Corrente
3.08.02                                              Diferido
3.09              Resultado Líquido das Operações Continuadas
3.10            Resultado Líquido de Operações Descontinuadas
3.10.01     Lucro/Prejuízo Líquido das Operações Descontin...
3.10.02     Ganhos/Perdas Líquidas sobre Ativos de Operaçõ...
3.11                    Lucro/Prejuízo Consolidado do Período
3.11.01            Atribuído a Sócios da Empresa Controladora
3.11.02                  Atribuído a Sócios Não Controladores
3.99                          Lucro por Ação - (Reais / Ação)
3.99.01                                 Lucro Básico por Ação
3.99.01.01                                                 ON
3.99.02                                Lucro Diluído por Ação
3.99.02.01                                                 ON
3.04.03.01  Ganhos (perdas) líquidas sobre contas a recebe...
3.04.03.01  Reversão (perda) por redução ao valor recuperá...
3.04.03.01               Reversão (perda) de crédito esperada

In [16]:
embraer.

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
7599,07.689.002/0001-89,2011-12-31,3,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.01,Receita de Venda de Bens e/ou Serviços,9858055.000,S
7601,07.689.002/0001-89,2011-12-31,3,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.02,Custo dos Bens e/ou Serviços Vendidos,-7638825.000,S
7603,07.689.002/0001-89,2011-12-31,3,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.03,Resultado Bruto,2219230.000,S
7605,07.689.002/0001-89,2011-12-31,3,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.04,Despesas/Receitas Operacionais,-1697502.000,S
7607,07.689.002/0001-89,2011-12-31,3,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-12-31,3.04.01,Despesas com Vendas,-702866.000,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368556,07.689.002/0001-89,2024-12-31,1,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-12-31,3.99,Lucro por Ação - (Reais / Ação),0.000,N
368558,07.689.002/0001-89,2024-12-31,1,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-12-31,3.99.01,Lucro Básico por Ação,0.000,N
368560,07.689.002/0001-89,2024-12-31,1,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-12-31,3.99.01.01,ON,2.612,N
368562,07.689.002/0001-89,2024-12-31,1,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-12-31,3.99.02,Lucro Diluído por Ação,0.000,N
368564,07.689.002/0001-89,2024-12-31,1,EMBRAER S.A.,20087,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-12-31,3.99.02.01,ON,2.612,N

In [17]:
from google.colab import files

embraer.to_excel('embraer.xlsx', index=False)
files.download('embraer.xlsx')